name: CI/CD Backend

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get current date and time
        id: date
        run: echo "DATE_TAG=$(date -u +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: backend
          push: true
          tags: |
            azaleh/diplodocu-backend:${{ env.DATE_TAG }}

      - name: Clone manifest repository
        uses: actions/checkout@v4
        with:
          repository: Maasym/portfolio-manifests
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          path: manifest-repo

      - name: Update manifest with new image tag
        run: |
          sed -i 's|^\(\s*image:\s*\).*|\1azaleh/diplodocu-backend:${{ env.DATE_TAG }}|' manifest-repo/diplodocu/backend/deployment.yaml

      - name: Commit and push updated manifest
        working-directory: manifest-repo
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "kitzune-no-aki"
          git add diplodocu/backend/deployment.yaml
          git commit -m "Update image tag to ${{ env.DATE_TAG }}"
          git push
        env:
          REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}